-- Todo certification support.
-- Run this in the Supabase SQL editor before using the todo UI.

CREATE TABLE IF NOT EXISTS todo_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT,
  user_name TEXT NOT NULL,
  todo_date DATE NOT NULL,
  title TEXT NOT NULL,
  proof_photo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS todo_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  title TEXT NOT NULL,
  weekdays INTEGER[] NOT NULL,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE,
  repeat_scope TEXT NOT NULL DEFAULT 'weekly',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE todo_items
  ADD COLUMN IF NOT EXISTS template_id BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'todo_items_template_id_fkey'
  ) THEN
    ALTER TABLE todo_items
      ADD CONSTRAINT todo_items_template_id_fkey
      FOREIGN KEY (template_id)
      REFERENCES todo_templates(id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS todo_items_user_date_idx
  ON todo_items (user_name, todo_date);

CREATE INDEX IF NOT EXISTS todo_items_date_idx
  ON todo_items (todo_date);

CREATE UNIQUE INDEX IF NOT EXISTS todo_items_template_date_unique_idx
  ON todo_items (template_id, todo_date)
  WHERE template_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS todo_templates_user_active_idx
  ON todo_templates (user_name, is_active);

ALTER TABLE todo_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE todo_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "todo_items_public_select" ON todo_items;
CREATE POLICY "todo_items_public_select"
ON todo_items FOR SELECT
USING (true);

DROP POLICY IF EXISTS "todo_items_public_insert" ON todo_items;
CREATE POLICY "todo_items_public_insert"
ON todo_items FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "todo_items_public_update" ON todo_items;
CREATE POLICY "todo_items_public_update"
ON todo_items FOR UPDATE
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "todo_templates_public_select" ON todo_templates;
CREATE POLICY "todo_templates_public_select"
ON todo_templates FOR SELECT
USING (true);

DROP POLICY IF EXISTS "todo_templates_public_insert" ON todo_templates;
CREATE POLICY "todo_templates_public_insert"
ON todo_templates FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "todo_templates_public_update" ON todo_templates;
CREATE POLICY "todo_templates_public_update"
ON todo_templates FOR UPDATE
USING (true)
WITH CHECK (true);
